name: flutter_keiko
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.8.0 # Asegúrate de usar la última versión disponible
  cupertino_icons: ^1.0.8
  cloud_firestore: ^4.5.0
  flutter_colorpicker: ^1.0.3
  flutter_vector_icons: ^2.0.0
  font_awesome_flutter: ^10.0.0
  audioplayers: ^6.1.0
  vibration: ^2.0.1
  shared_preferences: ^2.3.3
  emoji_picker_flutter: ^1.0.4
  uuid: ^3.0.6
  intl: ^0.18.0
  provider:  ^6.0.0
  flutter_datetime_picker: ^1.5.1
  firebase_messaging: ^14.7.10
  firebase_database: ^10.5.7
  syncfusion_flutter_charts: ^20.3.51
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/image/fond-home.png
    - assets/image/fond-home1.png


    - assets/sounds/
    - assets/music/

    - assets/sounds/notification1.mp3
    - assets/sounds/drum.mp3
    - assets/sounds/yoooo.mp3

    - assets/music/meditacion.mp3
    - assets/music/lluvia.mp3
    - assets/music/fogata.mp3

    - assets/image/japanese_background.jpg
    - assets/image/fondo-login.jpg
    - assets/image/icon.jpg
    - assets/image/icon.png

    - assets/image/pomodoro_config.jpg
    - assets/image/pomodoro_pause.jpg
    - assets/image/pomodoro_start.jpg

    - assets/image/vaso_lleno.png
    - assets/image/vaso_medio.png
    - assets/image/vaso_vacio.png

  uses-material-design: true
