name: Build Flutter APK

on:
  push:
    branches:
<<<<<<< HEAD
      - main  # Ejecutar cuando hagas un push a la rama principal (puedes cambiarla si usas otra)
  pull_request:
    branches:
      - main  # Ejecutar en pull request a la rama principal

jobs:
  build:
    runs-on: ubuntu-latest  # Usamos Ubuntu como sistema operativo

    steps:
      # Paso 1: Configurar Flutter
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.5.4'  # Usa la versión que necesites de Flutter

      # Paso 2: Instalar dependencias de Flutter
      - name: Install dependencies
        run: flutter pub get

      # Paso 3: Ejecutar la compilación para la APK
      - name: Build APK
        run: flutter build apk --release  # Cambia el tipo de build si lo necesitas (debug, profile, release)

      # Paso 4: Subir el APK como artefacto (opcional)
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk  # Ruta de salida del APK
=======
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        run: |
          git clone -b stable https://github.com/flutter/flutter.git
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          flutter/bin/flutter --version

      - name: Switch to stable channel
        run: flutter/bin/flutter channel stable

      - name: Install dependencies
        run: flutter/bin/flutter pub get

      - name: Build APK
        run: flutter/bin/flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk
>>>>>>> bead458eeaea04d93929ae91ea1a9de8319bc506
