name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        run: |
          git clone -b stable https://github.com/flutter/flutter.git
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          flutter/bin/flutter --version

      - name: Switch to stable channel
        run: flutter/bin/flutter channel stable

      - name: Install dependencies
        run: flutter/bin/flutter pub get

      - name: Build APK
        run: flutter/bin/flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk
